
create database hyundai_book

use hyundai_book

create table book_info (
	NO INT(11) unsigned NOT NULL,
	TITLE VARCHAR(50),
	ISBN VARCHAR(15),
	AUTHOR VARCHAR(20),
	DESCRIPTION VARCHAR(500),
	IMAGE VARCHAR(100),
	LINK VARCHAR(100),
	REGISTER VARCHAR(20),
	REGISTERED_DATE DATE,
	CREATEDATA DATE,
	AVALABILITY VARCHAR(10)
	);

create table book_log (
	BOOK_NO INT(11) unsigned NOT NULL,
	BOOK_LENDER VARCHAR(20),
	BOOK_LENDER_EMAIL varchar(30),
	BOOK_LENDDATE DATE NOT NULL,
	BOOK_RETURNDATE DATE
	)
	
